import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { RoomProvider } from '../context/RoomContext';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RoomProvider>
    <html lang="en">
      <body
        className={ `${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 h-screen flex` }
      >
        <aside className="w-64 bg-gray-800 text-white flex flex-col">
          <div className="p-4 bg-gray-900">
            <h1 className="text-xl font-bold text-center">Admin Logo</h1>
          </div>
          <nav className="flex-1 mt-4">
            <ul className="space-y-2">
              <li>
                <Link className="block py-2.5 px-4 rounded hover:bg-gray-700" href="/">Home</Link>
              </li>
            </ul>
          </nav>

        </aside>
        <main className="flex-1 p-6 bg-white">
          <header className="border-b pb-4 mb-6">
            <h2 className="text-2xl font-semibold">Dynamic Panel</h2>
          </header>

          <div className="space-y-4">
            <div className="bg-gray-100 p-4 rounded shadow">
              {children}
            </div>
          </div>
        </main>

      </body>
    </html >
    </RoomProvider>
  );
}
